# SwiftLint Configuration
# Basic configuration for the genie project

# Disable rules that are too strict for development
disabled_rules:
  - line_length
  - function_body_length
  - file_length
  - type_body_length
  - cyclomatic_complexity

# Opt-in rules that are useful but not enabled by default
opt_in_rules:
  - empty_count
  - force_unwrapping
  - implicitly_unwrapped_optional
  - overridden_super_call
  - redundant_nil_coalescing
  - vertical_whitespace

# Analyzer rules (only run by 'swiftlint analyze')
analyzer_rules:
  - unused_import

# Exclude certain directories and files
excluded:
  - Tests
  - docs
  - mcp
  - .build
  - Package.resolved

# Include only Swift files
included:
  - Sources

# Reporter configuration
reporter: "xcode"

# Cache configuration
cache_path: .swiftlint_cache 