if: tag IS blank
branches:
  only:
  - master
env:
  global:
  - SWIFT_BRANCH=swift-5.0.1-release
  - SWIFT_VERSION=swift-5.0.1-RELEASE
  - PACKAGE_VERSION=0.0.1
  - secure: jvZn90+GBN0w4F9tbrFbeD5oCoTNYsWrTAkTrydet+JbxLapXegZB3ul03lYEBpimwSWF+sSycJ7lrqkXhZ4PWk4Gu8DRSopiIkWmwHVGIDjNEOAFNhtbu6cuwjTYjqaA+N5L6/wsERA7+2iDEPHWtzdVe6RgrqDo9BHa5CJTaBMzpyl0RRGfDQoD4uBkLnlWdp31fnXTxmrRDsksQw5GuV0OjyEo0w06iuIohwDHc2qnStaz/dN/u5RoQynQtm9W1OeuI6rId+hmbf9K2Zf/yv6Q1NEK6yK0vW5MSB0wK7i7SNUkObJShBkBFJZbGjDSyK6d3EaQjrdwGGDHJOjPpD4B+8jmaPXM68l4KBifthucTk8SBWhlt2uhj2He9UBO3vnbzJi+EkPhzk5doSSoIEDncyCT9J1jTlfcCC+EZzOCXqlT/OhGvyxPAbaUkVUHDUXn/dDeXzJeZEVnUXOR1bH+Z8ZXjji1RzwFgHYa/UkxfETyFJYSAD2MTlGJ2457jb8kiTe/wGJ8h7wdg9NW5TG9PAph8HRdIvXCwUHSdvE9muNojsqRvH4LHXBBNd7Ul4Tx53gI+Owq/wO5HaFHwDyED4W4lk8hc5hZJ5EAPoh8zDEhGQGND/8VIQOK0GwWPbi5PyGlPLeJADUbXTG7h4qEFJBpsPYyGH986rs/KI=
jobs:
  include:
  - stage: Linux test
    os: linux
    language: generic
    dist: xenial
    sudo: required
    install:
    - sudo apt-get install clang libcurl3 libcurl4-openssl-dev libpython2.7 libpython2.7-dev
      libicu-dev libstdc++6
    - curl https://swift.org/builds/$SWIFT_BRANCH/ubuntu1604/$SWIFT_VERSION/$SWIFT_VERSION-ubuntu16.04.tar.gz
      > $SWIFT_VERSION-ubuntu16.04.tar.gz
    - tar xzf $SWIFT_VERSION-ubuntu16.04.tar.gz
    - export PATH="$(pwd)/$SWIFT_VERSION-ubuntu16.04/usr/bin:$PATH"
    script:
    - swift package update
    - swift test
  - stage: OSX test
    os: osx
    osx_image: xcode10.2
    language: swift
    sudo: required
    install:
    - wget https://swift.org/builds/$SWIFT_BRANCH/xcode/$SWIFT_VERSION/$SWIFT_VERSION-osx.pkg
    - sudo installer -pkg $SWIFT_VERSION-osx.pkg -target /
    - export PATH="/Library/Developer/Toolchains/$SWIFT_VERSION.xctoolchain/usr/bin:$PATH"
    script:
    - swift package update
    - swift test
#  - stage: Set tag
#    script:
#    - git config --global user.email "builds@travis-ci.com"
#    - git config --global user.name "Travis CI"
#    - git tag $PACKAGE_VERSION
#    - git push --quiet https://$GH_TOKEN@github.com/zachwick/SwiftHello --tag > /dev/null 2>&1
